package ru.kpfu.itis.android_hw

object QuestionsRepository {
    val list : List<Question> = listOf(
        Question("Какую музыку вы предпочитаете?",
            listOf(Option("Поп",false),
                Option("Рок", false),
                Option("Хип-хоп", false),
                Option("Классика",false),
                Option("Джаз",false),
                Option("Электронная",false),
                Option("Металл",false),
                Option("Регги",false))),
        Question("Какое ваше любимое время года?",
            listOf(Option("Весна",false),
                Option("Лето",false),
                Option("Осень",false),
                Option("Зима",false))),
        Question("Какие виды спорта вам интересны?",
            listOf(Option("Футбол",false),
                Option("Баскетбол",false),
                Option("Теннис",false),
                Option("Гольф",false),
                Option("Плавание",false),
                Option("Бег",false),
                Option("Бокс",false),
                Option("Волейбол",false),
                Option("Бадминтон",false))),
        Question("Какой ваш любимый цвет?",
            listOf(Option("Красный",false),
                Option("Синий",false),
                Option("Зеленый",false),
                Option("Желтый",false),
                Option("Розовый",false),
                Option("Фиолетовый",false),
                Option("Оранжевый",false),
                Option("Черный",false),
                Option("Белый",false))),
        Question("Какую еду вы предпочитаете?",
            listOf(Option("Итальянская",false),
                Option("Японская",false),
                Option("Мексиканская",false),
                Option("Китайская",false),
                Option("Французская",false),
                Option("Индийская",false),
                Option("Американская",false),
                Option("Тайская",false),
                Option("Русская",false))),
        Question("Какую книгу вы предпочитаете?",
            listOf(Option("Фантастика",false),
                Option("Детектив",false),
                Option("Классика",false),
                Option("Роман",false),
                Option("Приключения",false),
                Option("Научно-популярная",false),
                Option("Художественная проза",false),
                Option("Фэнтези",false))),
        Question("Какое ваше любимое животное?",
            listOf(Option("Собака",false),
                Option("Кот",false),
                Option("Лев",false),
                Option("Тигр",false),
                Option("Волк",false),
                Option("Обезьяна",false),
                Option("Птица",false),
                Option("Хомяк",false),
                Option("Лошадь",false))),
        Question("Какую программу вы предпочитаете для общения с друзьями?",
            listOf(Option("WhatsApp",false),
                Option("Telegram",false),
                Option("Viber",false),
                Option("Instagram",false),
                Option("Snapchat",false),
                Option("Facebook Messenger",false),
                Option("Discord",false),
                Option("Skype",false))),
        Question("Какой ваш любимый вид кино?",
            listOf(Option("Комедия",false),
                Option("Драма",false),
                Option("Триллер",false),
                Option("Фантастика",false),
                Option("Ужасы",false),
                Option("Боевик",false),
                Option("Мелодрама",false),
                Option("Документальный",false))),
        Question("Какой ваш любимый вид транспорта?",
            listOf(Option("Машина",false),
                Option("Велосипед",false),
                Option("Поезд",false),
                Option("Самолет",false),
                Option("Корабль",false),
                Option("Мотоцикл",false),
                Option("Автобус",false),
                Option("Трамвай",false))),
        Question("Какое ваше любимое хобби?",
            listOf(Option("Чтение",false),
                Option("Рисование",false),
                Option("Фотография",false),
                Option("Путешествия",false),
                Option("Готовка",false),
                Option("Спорт",false),
                Option("Игра на музыкальных инструментах",false),
                Option("Садоводство",false),
                Option("Коллекционирование",false))),
        Question("Какой ваш любимый вид технологий?",
            listOf(Option("Смартфоны",false),
                Option("Компьютеры",false),
                Option("Гаджеты для дома",false),
                Option("Автомобили",false),
                Option("Виртуальная реальность",false),
                Option("Дроны",false),
                Option("Роботы",false),
                Option("Интернет вещей",false))),
        Question("Какое ваше любимое место для отдыха?",
            listOf(Option("Пляж",false),
                Option("Горы",false),
                Option("Город",false),
                Option("Сельская местность",false),
                Option("Озеро",false),
                Option("Пустыня",false),
                Option("Зоопарк",false),
                Option("Парк аттракционов",false))),
        Question("Какую среду разработки вы предпочитаете?",
            listOf(Option("IntelliJ IDEA",false),
                Option("Eclipse",false),
                Option("Visual Studio Code",false),
                Option("Android Studio",false),
                Option("Xcode",false),
                Option("Sublime Text",false),
                Option("Vim",false),
                Option("Atom",false),
                Option("NetBeans",false)))
    )
}